spring:
  datasource:
    url: jdbc:h2:mem:book_library
    username: sa

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true