spring:
  datasource:
    url: jdbc:h2:mem:book_library
    username: sa
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true