spring:
    banner:
        location: banner.txt
    output:
        ansi:
            enabled: ALWAYS
    messages:
        basename: i18n/quizmessages
        encoding: UTF-8

csv:
    file:
        name: questions

correct:
    answers: 4

locale: ru_RU
